/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DPP_Order;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MongGu
 */
public class Order extends javax.swing.JFrame {
    
    int RowCount;
    String UserName;
    
    
    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        RowCount = 0;
        UserName = "고길동";
        
        UserNameField.setText(UserName + " 님");   // 고객 객체 정보 받아와서 고객이름 지정
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MenuTable = new javax.swing.JTable();
        NoCategories = new javax.swing.JPanel();
        DRINKPanel = new javax.swing.JPanel();
        DRINK_item_1 = new javax.swing.JLabel();
        DRINK_item_2 = new javax.swing.JLabel();
        DRINK_item_3 = new javax.swing.JLabel();
        DRINK_item_4 = new javax.swing.JLabel();
        DRINK_item_5 = new javax.swing.JLabel();
        DRINK_item_6 = new javax.swing.JLabel();
        FOODPanel = new javax.swing.JPanel();
        FOOD_item_1 = new javax.swing.JLabel();
        FOOD_item_2 = new javax.swing.JLabel();
        FOOD_item_3 = new javax.swing.JLabel();
        FOOD_item_4 = new javax.swing.JLabel();
        FOOD_item_5 = new javax.swing.JLabel();
        FOOD_item_6 = new javax.swing.JLabel();
        SNACKPanel = new javax.swing.JPanel();
        SNACK_item_1 = new javax.swing.JLabel();
        SNACK_item_2 = new javax.swing.JLabel();
        SNACK_item_3 = new javax.swing.JLabel();
        SNACK_item_4 = new javax.swing.JLabel();
        SNACK_item_5 = new javax.swing.JLabel();
        SNACK_item_6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BuyButton = new javax.swing.JLabel();
        RefrashButton = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 15, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("맑은 고딕", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("담은 메뉴");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        MenuTable.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        MenuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "메뉴", "가격"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MenuTable.setRowHeight(20);
        MenuTable.setShowVerticalLines(false);
        jScrollPane2.setViewportView(MenuTable);
        if (MenuTable.getColumnModel().getColumnCount() > 0) {
            MenuTable.getColumnModel().getColumn(0).setResizable(false);
            MenuTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 310));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 500));

        NoCategories.setBackground(new java.awt.Color(32, 47, 90));

        javax.swing.GroupLayout NoCategoriesLayout = new javax.swing.GroupLayout(NoCategories);
        NoCategories.setLayout(NoCategoriesLayout);
        NoCategoriesLayout.setHorizontalGroup(
            NoCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        NoCategoriesLayout.setVerticalGroup(
            NoCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(NoCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 690, 270));

        DRINKPanel.setBackground(new java.awt.Color(32, 47, 90));
        DRINKPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DRINK_item_1.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\coke.png")); // NOI18N
        DRINK_item_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DRINK_item_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DRINK_item_1MouseClicked(evt);
            }
        });
        DRINKPanel.add(DRINK_item_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        DRINK_item_2.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\cider.png")); // NOI18N
        DRINK_item_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DRINK_item_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DRINK_item_2MouseClicked(evt);
            }
        });
        DRINKPanel.add(DRINK_item_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        DRINK_item_3.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\fanta.png")); // NOI18N
        DRINK_item_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DRINK_item_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DRINK_item_3MouseClicked(evt);
            }
        });
        DRINKPanel.add(DRINK_item_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        DRINK_item_4.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\americano.png")); // NOI18N
        DRINK_item_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DRINK_item_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DRINK_item_4MouseClicked(evt);
            }
        });
        DRINKPanel.add(DRINK_item_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        DRINK_item_5.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\icetea.png")); // NOI18N
        DRINK_item_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DRINK_item_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DRINK_item_5MouseClicked(evt);
            }
        });
        DRINKPanel.add(DRINK_item_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        DRINK_item_6.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\smoothie.png")); // NOI18N
        DRINK_item_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DRINK_item_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DRINK_item_6MouseClicked(evt);
            }
        });
        DRINKPanel.add(DRINK_item_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        getContentPane().add(DRINKPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 690, 270));

        FOODPanel.setBackground(new java.awt.Color(32, 47, 90));
        FOODPanel.setMinimumSize(new java.awt.Dimension(650, 240));
        FOODPanel.setPreferredSize(new java.awt.Dimension(650, 240));
        FOODPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FOOD_item_1.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\ramen.png")); // NOI18N
        FOOD_item_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FOOD_item_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FOOD_item_1MouseClicked(evt);
            }
        });
        FOODPanel.add(FOOD_item_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        FOOD_item_2.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\friedRice.png")); // NOI18N
        FOOD_item_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FOOD_item_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FOOD_item_2MouseClicked(evt);
            }
        });
        FOODPanel.add(FOOD_item_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        FOOD_item_3.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\dduckbboki.png")); // NOI18N
        FOOD_item_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FOOD_item_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FOOD_item_3MouseClicked(evt);
            }
        });
        FOODPanel.add(FOOD_item_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        FOOD_item_4.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\addEgg.png")); // NOI18N
        FOOD_item_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FOOD_item_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FOOD_item_4MouseClicked(evt);
            }
        });
        FOODPanel.add(FOOD_item_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        FOOD_item_5.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\addCheeze.png")); // NOI18N
        FOOD_item_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FOOD_item_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FOOD_item_5MouseClicked(evt);
            }
        });
        FOODPanel.add(FOOD_item_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        FOOD_item_6.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\addRice.png")); // NOI18N
        FOOD_item_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FOOD_item_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FOOD_item_6MouseClicked(evt);
            }
        });
        FOODPanel.add(FOOD_item_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        getContentPane().add(FOODPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 690, 270));
        FOODPanel.getAccessibleContext().setAccessibleParent(this);

        SNACKPanel.setBackground(new java.awt.Color(32, 47, 90));
        SNACKPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SNACK_item_1.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\hotdog.png")); // NOI18N
        SNACK_item_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SNACK_item_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SNACK_item_1MouseClicked(evt);
            }
        });
        SNACKPanel.add(SNACK_item_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        SNACK_item_2.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\tacoyaki.png")); // NOI18N
        SNACK_item_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SNACK_item_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SNACK_item_2MouseClicked(evt);
            }
        });
        SNACKPanel.add(SNACK_item_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        SNACK_item_3.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\cheezeStick.png")); // NOI18N
        SNACK_item_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SNACK_item_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SNACK_item_3MouseClicked(evt);
            }
        });
        SNACKPanel.add(SNACK_item_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        SNACK_item_4.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\potatoFried.png")); // NOI18N
        SNACK_item_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SNACK_item_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SNACK_item_4MouseClicked(evt);
            }
        });
        SNACKPanel.add(SNACK_item_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        SNACK_item_5.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\ggang.png")); // NOI18N
        SNACK_item_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SNACK_item_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SNACK_item_5MouseClicked(evt);
            }
        });
        SNACKPanel.add(SNACK_item_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        SNACK_item_6.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\gorebab.png")); // NOI18N
        SNACK_item_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SNACK_item_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SNACK_item_6MouseClicked(evt);
            }
        });
        SNACKPanel.add(SNACK_item_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        getContentPane().add(SNACKPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 690, 270));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\exit.png")); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\user.png")); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 0, -1, 50));

        UserNameField.setEditable(false);
        UserNameField.setBackground(new java.awt.Color(255, 255, 255));
        UserNameField.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        UserNameField.setBorder(null);
        UserNameField.setFocusable(false);
        jPanel4.add(UserNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 90, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 690, 50));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\food.png")); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 22, -1, -1));

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
        jLabel4.setText("음식 주문");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 22, -1, -1));

        jLabel5.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        jLabel5.setText("메뉴를 담아서 주문해주세요.");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        BuyButton.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\order.png")); // NOI18N
        BuyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuyButtonMouseClicked(evt);
            }
        });
        jPanel5.add(BuyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        RefrashButton.setIcon(new javax.swing.ImageIcon("D:\\NetbeansProjects\\Design_Pattern_Project\\image\\reload.png")); // NOI18N
        RefrashButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RefrashButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefrashButtonMouseClicked(evt);
            }
        });
        jPanel5.add(RefrashButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 690, 110));

        jPanel7.setBackground(new java.awt.Color(32, 47, 90));

        jPanel6.setBackground(new java.awt.Color(106, 116, 145));

        jLabel7.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Categories");

        jLabel9.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("drink");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("food");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("snack");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(47, 47, 47)
                .addComponent(jLabel10)
                .addGap(41, 41, 41)
                .addComponent(jLabel11)
                .addGap(35, 35, 35))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 690, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        System.exit(0);     // 종료 버튼 클릭
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // drink 카테고리 선택
        DRINKPanel.setVisible(true);
        FOODPanel.setVisible(false);
        SNACKPanel.setVisible(false);
        NoCategories.setVisible(false);
        
        DRINKPanel.setEnabled(true);
        FOODPanel.setEnabled(false);
        SNACKPanel.setEnabled(false);
        NoCategories.setEnabled(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // food 카테고리 선택
        DRINKPanel.setVisible(false);
        FOODPanel.setVisible(true);
        SNACKPanel.setVisible(false);
        NoCategories.setVisible(false);
        
        DRINKPanel.setEnabled(false);
        FOODPanel.setEnabled(true);
        SNACKPanel.setEnabled(false);
        NoCategories.setEnabled(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // snack 카테고리 선택
        DRINKPanel.setVisible(false);
        FOODPanel.setVisible(false);
        SNACKPanel.setVisible(true);
        NoCategories.setVisible(false);
        
        DRINKPanel.setEnabled(false);
        FOODPanel.setEnabled(false);
        SNACKPanel.setEnabled(true);
        NoCategories.setEnabled(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void RefrashButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefrashButtonMouseClicked
        
        // 초기화 버튼 클릭
        
        for(int i=0; i<14; i++) {
            MenuTable.setValueAt("", i, 0);
            MenuTable.setValueAt("", i, 1);
        }
        
        RowCount = 0;
        
    }//GEN-LAST:event_RefrashButtonMouseClicked

    private void DRINK_item_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DRINK_item_1MouseClicked
        
        // 콜라 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("콜라", RowCount, 0);
            MenuTable.setValueAt(1500, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
        
        //String CourseName = (String) MenuTable.getValueAt(selectedRow, 1);
    }//GEN-LAST:event_DRINK_item_1MouseClicked

    private void BuyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuyButtonMouseClicked
        
        // 구매 버튼 클릭
        
        if(RowCount == 0) { // 메뉴를 아무것도 고르지 않았을 경우
            JOptionPane.showInternalMessageDialog(null, "메뉴를 골라주세요.");
            
        } else {        // 정상적으로 주문이 되었을 경우
                        
            String filePath = "c:\\Temp\\test.txt";           // 저장할 임시 파일 경로
            int cost = 0;       // 총 주문 금액
            String orderText = "";      // 주문 내역
            
            for(int i=0; i<RowCount; i++) {
                orderText += (String) MenuTable.getValueAt(i,0) + ", ";
            }
            
            
            for(int i=0; i<RowCount; i++) {
                // cost[i] = (int) MenuTable.getValueAt(i,1);
                cost += (int) MenuTable.getValueAt(i,1);
            }
            
                        
            try {
                FileWriter fileWriter = new FileWriter(filePath, true);
                fileWriter.write(UserName + "님의 주문 : " + orderText + "총 주문 금액 = " + cost + "\n\n");
                fileWriter.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
            
            for(int i=0; i<14; i++) {
                MenuTable.setValueAt("", i, 0);
                MenuTable.setValueAt("", i, 1);
            }
            RowCount = 0;
            
            JOptionPane.showInternalMessageDialog(null, "주문이 접수되었습니다.");
        }
        
    }//GEN-LAST:event_BuyButtonMouseClicked

    private void DRINK_item_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DRINK_item_2MouseClicked
        // 사이다 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("사이다", RowCount, 0);
            MenuTable.setValueAt(1400, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_DRINK_item_2MouseClicked

    private void DRINK_item_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DRINK_item_3MouseClicked
        // 환타 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("환타", RowCount, 0);
            MenuTable.setValueAt(1200, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_DRINK_item_3MouseClicked

    private void DRINK_item_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DRINK_item_4MouseClicked
        // 아메리카노 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("아메리카노", RowCount, 0);
            MenuTable.setValueAt(2100, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_DRINK_item_4MouseClicked

    private void DRINK_item_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DRINK_item_5MouseClicked
        // 아이스티 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("아이스티", RowCount, 0);
            MenuTable.setValueAt(1900, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_DRINK_item_5MouseClicked

    private void DRINK_item_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DRINK_item_6MouseClicked
        // 스무디 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("스무디", RowCount, 0);
            MenuTable.setValueAt(2500, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_DRINK_item_6MouseClicked

    private void FOOD_item_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOOD_item_1MouseClicked
        // 라면 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("라면", RowCount, 0);
            MenuTable.setValueAt(3000, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_FOOD_item_1MouseClicked

    private void FOOD_item_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOOD_item_2MouseClicked
        // 볶음밥 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("볶음밥", RowCount, 0);
            MenuTable.setValueAt(3500, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_FOOD_item_2MouseClicked

    private void FOOD_item_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOOD_item_3MouseClicked
        // 떡볶이 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("떡볶이", RowCount, 0);
            MenuTable.setValueAt(4000, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_FOOD_item_3MouseClicked

    private void FOOD_item_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOOD_item_4MouseClicked
        // 계란추가 클릭
       
        if (RowCount < 14) {
            MenuTable.setValueAt("계란추가", RowCount, 0);
            MenuTable.setValueAt(500, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_FOOD_item_4MouseClicked

    private void FOOD_item_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOOD_item_5MouseClicked
        // 치즈추가 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("치즈추가", RowCount, 0);
            MenuTable.setValueAt(500, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_FOOD_item_5MouseClicked

    private void FOOD_item_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOOD_item_6MouseClicked
        // 밥추가 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("밥추가", RowCount, 0);
            MenuTable.setValueAt(1000, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_FOOD_item_6MouseClicked

    private void SNACK_item_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SNACK_item_1MouseClicked
        // 핫도그 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("핫도그", RowCount, 0);
            MenuTable.setValueAt(2300, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_SNACK_item_1MouseClicked

    private void SNACK_item_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SNACK_item_2MouseClicked
        // 타코야키 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("타코야키", RowCount, 0);
            MenuTable.setValueAt(3000, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_SNACK_item_2MouseClicked

    private void SNACK_item_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SNACK_item_3MouseClicked
        // 치즈스틱 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("치즈스틱", RowCount, 0);
            MenuTable.setValueAt(2200, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_SNACK_item_3MouseClicked

    private void SNACK_item_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SNACK_item_4MouseClicked
        // 감자튀김 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("감자튀김", RowCount, 0);
            MenuTable.setValueAt(2500, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_SNACK_item_4MouseClicked

    private void SNACK_item_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SNACK_item_5MouseClicked
        // 새우깡 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("새우깡", RowCount, 0);
            MenuTable.setValueAt(1500, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_SNACK_item_5MouseClicked

    private void SNACK_item_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SNACK_item_6MouseClicked
        // 고래밥 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("고래밥", RowCount, 0);
            MenuTable.setValueAt(1000, RowCount, 1);
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_SNACK_item_6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuyButton;
    private javax.swing.JPanel DRINKPanel;
    private javax.swing.JLabel DRINK_item_1;
    private javax.swing.JLabel DRINK_item_2;
    private javax.swing.JLabel DRINK_item_3;
    private javax.swing.JLabel DRINK_item_4;
    private javax.swing.JLabel DRINK_item_5;
    private javax.swing.JLabel DRINK_item_6;
    private javax.swing.JPanel FOODPanel;
    private javax.swing.JLabel FOOD_item_1;
    private javax.swing.JLabel FOOD_item_2;
    private javax.swing.JLabel FOOD_item_3;
    private javax.swing.JLabel FOOD_item_4;
    private javax.swing.JLabel FOOD_item_5;
    private javax.swing.JLabel FOOD_item_6;
    private javax.swing.JTable MenuTable;
    private javax.swing.JPanel NoCategories;
    private javax.swing.JLabel RefrashButton;
    private javax.swing.JPanel SNACKPanel;
    private javax.swing.JLabel SNACK_item_1;
    private javax.swing.JLabel SNACK_item_2;
    private javax.swing.JLabel SNACK_item_3;
    private javax.swing.JLabel SNACK_item_4;
    private javax.swing.JLabel SNACK_item_5;
    private javax.swing.JLabel SNACK_item_6;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
