package DPP_Order;

import DPP_Login.LoginLog;
import javax.swing.JOptionPane;
import java.io.*;

/**
 *
 * @author MongGu
 */
public class Order extends javax.swing.JFrame {
    LoginLog loginlog = new LoginLog();
    static int friedricenum = 0;
    static int tteokbokkinum = 0;
    static int ramennum = 0;
    static int addegg = 0;
    static int addcheese = 0;
    static int addrice = 0;
    
    static int americanoNum = 0;
    static int cafeLatteNum = 0;
    static int addShotNum = 0;
    static int addCreamNum = 0;
    static int addMilkNum = 0;
    
    int RowCount;
    int TotalPrice;
    String UserName;
        
    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        
        DRINKPanel.setVisible(false);
        FOODPanel.setVisible(false);
        SNACKPanel.setVisible(false);
        NoCategories.setVisible(true);
        
        DRINKPanel.setEnabled(false);
        FOODPanel.setEnabled(false);
        SNACKPanel.setEnabled(false);
        NoCategories.setEnabled(true);
        
        RowCount = 0;
        UserName = loginlog.getName();
        TotalPrice = 0;
        
        UserNameField.setText(UserName + " 님");   // 고객 객체 정보 받아와서 고객이름 지정
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodDeco = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        addEgg = new javax.swing.JButton();
        addCheeze = new javax.swing.JButton();
        addRice = new javax.swing.JButton();
        foodOK = new javax.swing.JButton();
        drinkDeco = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        drinkOK = new javax.swing.JButton();
        addMilk = new javax.swing.JButton();
        addCream = new javax.swing.JButton();
        addShot = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MenuTable = new javax.swing.JTable();
        TotalPriceTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NoCategories = new javax.swing.JPanel();
        DRINKPanel = new javax.swing.JPanel();
        coke = new javax.swing.JButton();
        cyder = new javax.swing.JButton();
        fanta = new javax.swing.JButton();
        FOODPanel = new javax.swing.JPanel();
        dduckbboki = new javax.swing.JButton();
        friedRice = new javax.swing.JButton();
        ramen = new javax.swing.JButton();
        SNACKPanel = new javax.swing.JPanel();
        friedPotato = new javax.swing.JButton();
        hotDog = new javax.swing.JButton();
        cheezeStick = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        UserNameField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        order = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        foodDeco.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        foodDeco.setMinimumSize(new java.awt.Dimension(500, 270));

        jPanel1.setBackground(new java.awt.Color(106, 116, 145));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addEgg.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        addEgg.setText("<html>\n<center>\n계란 추가<br>\n(500원)\n</html>");
        addEgg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addEgg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEggMouseClicked(evt);
            }
        });
        jPanel1.add(addEgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, 102));

        addCheeze.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        addCheeze.setText("<html>\n<center>\n치즈 추가<br>\n(500원)\n</html>");
        addCheeze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCheeze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCheezeMouseClicked(evt);
            }
        });
        jPanel1.add(addCheeze, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 140, 102));

        addRice.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        addRice.setText("<html>\n<center>\n밥 추가<br>\n(1000원)\n</html>");
        addRice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addRice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addRiceMouseClicked(evt);
            }
        });
        jPanel1.add(addRice, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 140, 102));

        foodOK.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        foodOK.setText("선택 완료");
        foodOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        foodOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodOKMouseClicked(evt);
            }
        });
        jPanel1.add(foodOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 160, 50));

        javax.swing.GroupLayout foodDecoLayout = new javax.swing.GroupLayout(foodDeco.getContentPane());
        foodDeco.getContentPane().setLayout(foodDecoLayout);
        foodDecoLayout.setHorizontalGroup(
            foodDecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        foodDecoLayout.setVerticalGroup(
            foodDecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        drinkDeco.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        drinkDeco.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(106, 116, 145));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        drinkOK.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        drinkOK.setText("선택 완료");
        drinkOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        drinkOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drinkOKMouseClicked(evt);
            }
        });
        jPanel3.add(drinkOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 160, 50));

        addMilk.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        addMilk.setText("<html>\n<center>\n우유 추가<br>\n(400원)\n</html>");
        addMilk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMilk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMilkMouseClicked(evt);
            }
        });
        jPanel3.add(addMilk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 140, 102));

        addCream.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        addCream.setText("<html>\n<center>\n크림 추가<br>\n(500원)\n</html>");
        addCream.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCream.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCreamMouseClicked(evt);
            }
        });
        jPanel3.add(addCream, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, 102));

        addShot.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        addShot.setText("<html>\n<center>\n샷 추가<br>\n(300원)\n</html>");
        addShot.setToolTipText("");
        addShot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addShot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addShotMouseClicked(evt);
            }
        });
        jPanel3.add(addShot, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 140, 102));

        drinkDeco.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 270));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 15, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("맑은 고딕", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("담은 메뉴");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        MenuTable.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        MenuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "메뉴", "가격"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MenuTable.setRowHeight(20);
        MenuTable.setShowVerticalLines(false);
        jScrollPane2.setViewportView(MenuTable);
        if (MenuTable.getColumnModel().getColumnCount() > 0) {
            MenuTable.getColumnModel().getColumn(0).setResizable(false);
            MenuTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 230, 310));

        TotalPriceTextField.setBackground(new java.awt.Color(0, 15, 80));
        TotalPriceTextField.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        TotalPriceTextField.setForeground(new java.awt.Color(204, 204, 204));
        TotalPriceTextField.setToolTipText("");
        TotalPriceTextField.setBorder(null);
        jPanel2.add(TotalPriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 110, 60));

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("총 가격 : ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 500));

        NoCategories.setBackground(new java.awt.Color(32, 47, 90));

        javax.swing.GroupLayout NoCategoriesLayout = new javax.swing.GroupLayout(NoCategories);
        NoCategories.setLayout(NoCategoriesLayout);
        NoCategoriesLayout.setHorizontalGroup(
            NoCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        NoCategoriesLayout.setVerticalGroup(
            NoCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(NoCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 600, 270));

        DRINKPanel.setBackground(new java.awt.Color(32, 47, 90));
        DRINKPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coke.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        coke.setText("<html>\n<center>\n콜라<br>\n(1500원)\n</html>");
        coke.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        coke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cokeMouseClicked(evt);
            }
        });
        DRINKPanel.add(coke, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 160, 110));

        cyder.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        cyder.setText("<html>\n<center>\n아메리카노<br>\n(2000원)\n</html>");
        cyder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cyder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cyderMouseClicked(evt);
            }
        });
        DRINKPanel.add(cyder, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 160, 110));

        fanta.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        fanta.setText("<html>\n<center>\n카페라떼<br>\n(2800원)\n</html>");
        fanta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fanta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fantaMouseClicked(evt);
            }
        });
        DRINKPanel.add(fanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 160, 110));

        getContentPane().add(DRINKPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 600, 270));

        FOODPanel.setBackground(new java.awt.Color(32, 47, 90));
        FOODPanel.setMinimumSize(new java.awt.Dimension(650, 240));
        FOODPanel.setPreferredSize(new java.awt.Dimension(650, 240));
        FOODPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dduckbboki.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        dduckbboki.setText("<html>\n<center>\n떡볶이<br>\n(4000원)\n</html>");
        dduckbboki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dduckbbokiMouseClicked(evt);
            }
        });
        FOODPanel.add(dduckbboki, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 160, 110));

        friedRice.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        friedRice.setText("<html>\n<center>\n볶음밥<br>\n(3500원)\n</html>");
        friedRice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friedRiceMouseClicked(evt);
            }
        });
        FOODPanel.add(friedRice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 160, 110));

        ramen.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        ramen.setText("<html>\n<center>\n라면<br>\n(3000원)\n</html>");
        ramen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ramenMouseClicked(evt);
            }
        });
        FOODPanel.add(ramen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 160, 110));

        getContentPane().add(FOODPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 600, 270));
        FOODPanel.getAccessibleContext().setAccessibleParent(this);

        SNACKPanel.setBackground(new java.awt.Color(32, 47, 90));
        SNACKPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        friedPotato.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        friedPotato.setText("<html>\n<center>\n감자튀김<br>\n(2500원)\n</html>");
        friedPotato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friedPotatoMouseClicked(evt);
            }
        });
        SNACKPanel.add(friedPotato, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 160, 110));

        hotDog.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        hotDog.setText("<html>\n<center>\n핫도그<br>\n(2300원)\n</html>");
        hotDog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hotDogMouseClicked(evt);
            }
        });
        SNACKPanel.add(hotDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 160, 110));

        cheezeStick.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        cheezeStick.setText("<html>\n<center>\n치즈스틱<br>\n(2100원)\n</html>");
        cheezeStick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cheezeStickMouseClicked(evt);
            }
        });
        SNACKPanel.add(cheezeStick, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 160, 110));

        getContentPane().add(SNACKPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 600, 270));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserNameField.setEditable(false);
        UserNameField.setBackground(new java.awt.Color(255, 255, 255));
        UserNameField.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        UserNameField.setBorder(null);
        UserNameField.setFocusable(false);
        jPanel4.add(UserNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 90, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 690, 50));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
        jLabel4.setText("음식 주문");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("맑은 고딕", 0, 15)); // NOI18N
        jLabel5.setText("메뉴를 담아서 주문해주세요.");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        refresh.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        refresh.setText("초기화");
        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });
        jPanel5.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 110, 50));

        order.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        order.setText("주문하기");
        order.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderMouseClicked(evt);
            }
        });
        jPanel5.add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 110, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 690, 110));

        jPanel7.setBackground(new java.awt.Color(32, 47, 90));

        jPanel6.setBackground(new java.awt.Color(106, 116, 145));

        jLabel7.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Categories");

        jLabel9.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("drink");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("food");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("snack");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(47, 47, 47)
                .addComponent(jLabel10)
                .addGap(41, 41, 41)
                .addComponent(jLabel11)
                .addGap(35, 35, 35))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 600, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // drink 카테고리 선택
        DRINKPanel.setVisible(true);
        FOODPanel.setVisible(false);
        SNACKPanel.setVisible(false);
        NoCategories.setVisible(false);
        
        DRINKPanel.setEnabled(true);
        FOODPanel.setEnabled(false);
        SNACKPanel.setEnabled(false);
        NoCategories.setEnabled(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // food 카테고리 선택
        DRINKPanel.setVisible(false);
        FOODPanel.setVisible(true);
        SNACKPanel.setVisible(false);
        NoCategories.setVisible(false);
        
        DRINKPanel.setEnabled(false);
        FOODPanel.setEnabled(true);
        SNACKPanel.setEnabled(false);
        NoCategories.setEnabled(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // snack 카테고리 선택
        DRINKPanel.setVisible(false);
        FOODPanel.setVisible(false);
        SNACKPanel.setVisible(true);
        NoCategories.setVisible(false);
        
        DRINKPanel.setEnabled(false);
        FOODPanel.setEnabled(false);
        SNACKPanel.setEnabled(true);
        NoCategories.setEnabled(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        // 초기화 버튼 클릭
        
        for(int i=0; i<14; i++) {
            MenuTable.setValueAt("", i, 0);
            MenuTable.setValueAt("", i, 1);
        }
        
        RowCount = 0;
        
    }//GEN-LAST:event_refreshMouseClicked

    private void orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseClicked
        // 주문 버튼 클릭
        
        if(RowCount == 0) { // 메뉴를 아무것도 고르지 않았을 경우
            JOptionPane.showInternalMessageDialog(null, "메뉴를 골라주세요.");
            
        } else {        // 정상적으로 주문이 되었을 경우
                        
            String filePath = "c:\\Temp\\test.txt";           // 저장할 임시 파일 경로
            //int cost = 0;       // 총 주문 금액
            String orderText = "";      // 주문 내역
            
            for(int i=0; i<RowCount; i++) {
                orderText += (String) MenuTable.getValueAt(i,0);
                if(i != RowCount-1) {
                    orderText += ", ";
                }
            }
            
            
//            for(int i=0; i<RowCount; i++) {
//                // cost[i] = (int) MenuTable.getValueAt(i,1);
//                cost += (int) MenuTable.getValueAt(i,1);
//            }
            
                        
            try {
                FileWriter fileWriter = new FileWriter(filePath, true);
                fileWriter.write(UserName + "님의 주문 : " + orderText + "\n" + UserName + "님의 총 주문 금액 = " + TotalPrice + " 원\n\n");
                fileWriter.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
            
            for(int i=0; i<14; i++) {
                MenuTable.setValueAt("", i, 0);
                MenuTable.setValueAt("", i, 1);
            }
            RowCount = 0;
            
            JOptionPane.showInternalMessageDialog(null, "주문이 접수되었습니다.");
        }
        
    }//GEN-LAST:event_orderMouseClicked

    private void cokeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cokeMouseClicked
        // 콜라 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("콜라", RowCount, 0);
            MenuTable.setValueAt(1500, RowCount, 1);
            
            TotalPrice += 1500;
            TotalPriceTextField.setText(Integer.toString(TotalPrice));
            
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_cokeMouseClicked

    private void cyderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cyderMouseClicked
        // 아메리카노 클릭
        
        americanoNum = 1;
        
        if (RowCount < 14) {
            MenuTable.setValueAt("아메리카노", RowCount, 0);
            MenuTable.setValueAt(2000, RowCount, 1);
            
            drinkDeco.setVisible(true);
            drinkDeco.setLocation(200, 200);
            drinkDeco.setSize(510, 300);
            
            TotalPrice += 2000;
            TotalPriceTextField.setText(Integer.toString(TotalPrice));
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_cyderMouseClicked

    private void fantaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fantaMouseClicked
        // 카페라떼 클릭
        
        cafeLatteNum = 1;
        
        if (RowCount < 14) {
            MenuTable.setValueAt("카페라떼", RowCount, 0);
            MenuTable.setValueAt(2800, RowCount, 1);
            
            drinkDeco.setVisible(true);
            drinkDeco.setLocation(200, 200);
            drinkDeco.setSize(510, 300);
            
            TotalPrice += 2800;
            TotalPriceTextField.setText(Integer.toString(TotalPrice));
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_fantaMouseClicked

    private void ramenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ramenMouseClicked
        // 라면 클릭
        
        ramennum = 1;
        
        if (RowCount < 14) {
            MenuTable.setValueAt("라면", RowCount, 0);
            MenuTable.setValueAt(3000, RowCount, 1);
            
            foodDeco.setVisible(true);
            foodDeco.setLocation(200, 200);
            foodDeco.setSize(510, 300);
            
            TotalPrice += 3000;
            TotalPriceTextField.setText(Integer.toString(TotalPrice));

            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_ramenMouseClicked

    private void friedRiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friedRiceMouseClicked
        // 볶음밥 클릭
        
        friedricenum = 1;
        
        if (RowCount < 14) {
            MenuTable.setValueAt("볶음밥", RowCount, 0);
            MenuTable.setValueAt(3500, RowCount, 1);
            
            foodDeco.setVisible(true);
            foodDeco.setLocation(200, 200);
            foodDeco.setSize(510, 300);
            
            TotalPrice += 3500;
            TotalPriceTextField.setText(Integer.toString(TotalPrice));
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_friedRiceMouseClicked

    private void dduckbbokiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dduckbbokiMouseClicked
        // 떡볶이 클릭
        
        tteokbokkinum = 1;
        
        if (RowCount < 14) {
            MenuTable.setValueAt("떡볶이", RowCount, 0);
            MenuTable.setValueAt(4000, RowCount, 1);
            
            foodDeco.setVisible(true);
            foodDeco.setLocation(200, 200);
            foodDeco.setSize(510, 300);
            
            TotalPrice += 4000;
            TotalPriceTextField.setText(Integer.toString(TotalPrice));
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_dduckbbokiMouseClicked

    private void hotDogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hotDogMouseClicked
        // 핫도그 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("핫도그", RowCount, 0);
            MenuTable.setValueAt(2300, RowCount, 1);
            
            TotalPrice += 2300;
            TotalPriceTextField.setText(Integer.toString(TotalPrice));
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_hotDogMouseClicked

    private void cheezeStickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cheezeStickMouseClicked
        // 치즈스틱 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("치즈스틱", RowCount, 0);
            MenuTable.setValueAt(2100, RowCount, 1);
            
            TotalPrice += 2100;
            TotalPriceTextField.setText(Integer.toString(TotalPrice));
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_cheezeStickMouseClicked

    private void friedPotatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friedPotatoMouseClicked
        // 감자튀김 클릭
        
        if (RowCount < 14) {
            MenuTable.setValueAt("감자튀김", RowCount, 0);
            MenuTable.setValueAt(2500, RowCount, 1);
            
            TotalPrice += 2500;
            TotalPriceTextField.setText(Integer.toString(TotalPrice));
        
            RowCount++;
        } else {
            JOptionPane.showInternalMessageDialog(null, "더 이상 주문할 수 없습니다.");
        }
    }//GEN-LAST:event_friedPotatoMouseClicked

    private void addEggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEggMouseClicked
        // 계란 추가 클릭
        addegg++;
        
        MenuTable.setValueAt(" + 계란 추가", RowCount, 0);
        MenuTable.setValueAt(" + 500", RowCount, 1);
        
        TotalPrice += 500;
        TotalPriceTextField.setText(Integer.toString(TotalPrice));
        
        RowCount++;
    }//GEN-LAST:event_addEggMouseClicked

    private void addCheezeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCheezeMouseClicked
        // 치즈 추가 클릭
        addcheese++;
        
        MenuTable.setValueAt(" + 치즈 추가", RowCount, 0);
        MenuTable.setValueAt(" + 500", RowCount, 1);
        
        TotalPrice += 500;
        TotalPriceTextField.setText(Integer.toString(TotalPrice));
        
        RowCount++;
    }//GEN-LAST:event_addCheezeMouseClicked

    private void addRiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRiceMouseClicked
        // 밥 추가 클릭
        addrice++;
        
        MenuTable.setValueAt(" + 밥 추가", RowCount, 0);
        MenuTable.setValueAt(" + 1000", RowCount, 1);
        
        TotalPrice += 1000;
        TotalPriceTextField.setText(Integer.toString(TotalPrice));
        
        RowCount++;
    }//GEN-LAST:event_addRiceMouseClicked

    private void foodOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodOKMouseClicked
        // 선택 완료 클릭
        
        if(ramennum > 0){
            
            Food ramen = new Ramen();
            
            for(int i=0;i<addegg;i++){
                ramen = new AddEgg(ramen);
            }
            for(int i=0;i<addcheese;i++){
                ramen = new AddCheese(ramen);
            }
            for(int i=0;i<addrice;i++){
                ramen = new AddRice(ramen);
            }
            
            JOptionPane.showMessageDialog(null, ramen.getFoodName()+"하셨습니다.\n총 가격은"+ramen.cost()+"입니다.");
               
            ramennum = 0;
            addegg = 0;
            addcheese = 0;
            addrice = 0;
            
            foodDeco.setVisible(false);
            
        }else if(tteokbokkinum > 0){
            
            Food teokbokki = new Tteokbokki();
            
            for(int i=0;i<addegg;i++){
                teokbokki = new AddEgg(teokbokki);
            }
            for(int i=0;i<addcheese;i++){
                teokbokki = new AddCheese(teokbokki);
            }
            for(int i=0;i<addrice;i++){
                teokbokki = new AddRice(teokbokki);
            }
            JOptionPane.showMessageDialog(null, teokbokki.getFoodName()+"하셨습니다.\n총 가격은"+teokbokki.cost()+"입니다.");
    
            tteokbokkinum=0;
            addegg = 0;
            addcheese = 0;
            addrice = 0;
            
            foodDeco.setVisible(false);
            
        }else if(friedricenum > 0){
            
            Food friedrice = new FriedRice();
            
            for(int i=0;i<addegg;i++){
                friedrice = new AddEgg(friedrice);
            }
            for(int i=0;i<addcheese;i++){
                friedrice = new AddCheese(friedrice);
            }
            for(int i=0;i<addrice;i++){
                friedrice = new AddRice(friedrice);
            }
            JOptionPane.showMessageDialog(null, friedrice.getFoodName()+"하셨습니다.\n총 가격은"+friedrice.cost()+"입니다.");

            friedricenum=0;
            addegg = 0;
            addcheese = 0;
            addrice = 0;
            
            foodDeco.setVisible(false);
            
        }
    }//GEN-LAST:event_foodOKMouseClicked

    private void drinkOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drinkOKMouseClicked
        // 음료 선택완료 클릭
        
        if(americanoNum > 0){
            
            Drink americano = new Americano();
                        
            for(int i=0;i<addCreamNum;i++){
                americano = new AddCream(americano);
            }
            for(int i=0;i<addMilkNum;i++){
                americano = new AddMilk(americano);
            }
            for(int i=0;i<addShotNum;i++){
                americano = new AddShot(americano);
            }
            
            JOptionPane.showMessageDialog(null, americano.getDrinkName()+"하셨습니다.\n총 가격은"+americano.cost()+"입니다.");
                        
            americanoNum = 0;
            addCreamNum = 0;
            addMilkNum = 0;
            addShotNum = 0;
            
            drinkDeco.setVisible(false);
            
        }else if (cafeLatteNum > 0){
            
            Drink cafeLatte = new CafeLatte();
                        
            for(int i=0;i<addCreamNum;i++){
                cafeLatte = new AddCream(cafeLatte);
            }
            for(int i=0;i<addMilkNum;i++){
                cafeLatte = new AddMilk(cafeLatte);
            }
            for(int i=0;i<addShotNum;i++){
                cafeLatte = new AddShot(cafeLatte);
            }
            
            JOptionPane.showMessageDialog(null, cafeLatte.getDrinkName()+"하셨습니다.\n총 가격은"+cafeLatte.cost()+"입니다.");
                        
            americanoNum = 0;
            addCreamNum = 0;
            addMilkNum = 0;
            addShotNum = 0;
            
            drinkDeco.setVisible(false);
            
        }

    }//GEN-LAST:event_drinkOKMouseClicked

    private void addMilkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMilkMouseClicked
        // 우유 추가 클릭
        
        addMilkNum++;
        
        MenuTable.setValueAt(" + 우유 추가", RowCount, 0);
        MenuTable.setValueAt(" + 400", RowCount, 1);
        
        TotalPrice += 400;
        TotalPriceTextField.setText(Integer.toString(TotalPrice));
        
        RowCount++;

    }//GEN-LAST:event_addMilkMouseClicked

    private void addCreamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCreamMouseClicked
        // 크림 추가 클릭
        
        addCreamNum++;
        
        MenuTable.setValueAt(" + 크림 추가", RowCount, 0);
        MenuTable.setValueAt(" + 500", RowCount, 1);
        
        TotalPrice += 500;
        TotalPriceTextField.setText(Integer.toString(TotalPrice));
        
        RowCount++;

    }//GEN-LAST:event_addCreamMouseClicked

    private void addShotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addShotMouseClicked
        // 샷 추가 클릭
        
        addShotNum++;
        
        MenuTable.setValueAt(" + 샷 추가", RowCount, 0);
        MenuTable.setValueAt(" + 300", RowCount, 1);
        
        TotalPrice += 300;
        TotalPriceTextField.setText(Integer.toString(TotalPrice));
        
        RowCount++;

    }//GEN-LAST:event_addShotMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DRINKPanel;
    private javax.swing.JPanel FOODPanel;
    private javax.swing.JTable MenuTable;
    private javax.swing.JPanel NoCategories;
    private javax.swing.JPanel SNACKPanel;
    private javax.swing.JTextField TotalPriceTextField;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JButton addCheeze;
    private javax.swing.JButton addCream;
    private javax.swing.JButton addEgg;
    private javax.swing.JButton addMilk;
    private javax.swing.JButton addRice;
    private javax.swing.JButton addShot;
    private javax.swing.JButton cheezeStick;
    private javax.swing.JButton coke;
    private javax.swing.JButton cyder;
    private javax.swing.JButton dduckbboki;
    private javax.swing.JFrame drinkDeco;
    private javax.swing.JButton drinkOK;
    private javax.swing.JButton fanta;
    private javax.swing.JFrame foodDeco;
    private javax.swing.JButton foodOK;
    private javax.swing.JButton friedPotato;
    private javax.swing.JButton friedRice;
    private javax.swing.JButton hotDog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton order;
    private javax.swing.JButton ramen;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}
